# Generated by Django 3.2.9 on 2023-08-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=10),
        ),
    ]
